### ISSUE TITLE
Default region not set to us-east-1

### ISSUE THREAD

**Issue by dtougas** [UnivaCorporation/tortuga-kit-awsadapter#1]
When adding new nodes, the AMI may not be available if the adapter is attempting to spin up a node in a different region by default. When spinning up a new node, I got an error message that said:

`Reported: Error accessing AMI [ami-xxxxxxx] (The image id '[ami-xxxxxxx]' does not exist)`

The workaround was to do the following:

`adapter-mgmt update -r aws -p default -s region=us-east-1`

**Comment by EmmEff** [comment]
Fixed in merge #9
