### ISSUE TITLE
Unhelpful error message if subnet_id not set

### ISSUE THREAD

**Issue by dtougas** [UnivaCorporation/tortuga-kit-awsadapter#2]
If a `subnet_id` is not set, the following error will be generated when attempting to add nodes:

`Reported: AWS error: The security group 'sg-xxxxxxx' does not exist`

We should have a more helpful error message here.

**Comment by EmmEff** [comment]
`securitygroup` is not a required setting; AWS will use a default if none provided.

Warning message is now logged if undefined.

See merge #57
